name: Development pipeline

on:
  push:
    branches:
      - main

jobs:
  development_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: action/setup-node@v2
        with:
          node-version: '16'
      - name: Pre install
        run: ls
      - name: install
        run: npm install
      - name: Post install
        run: ls
